spring:
  h2:
    console:
      enabled: true # localhost:8080/h2-console 로 접속 가능하도록 한다.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
server:
  port: 8070